"""items table

Revision ID: ba484e693683
Revises: 
Create Date: 2025-04-22 20:23:24.995510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba484e693683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container',
    sa.Column('container_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('parent_container_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_container_id'], ['container.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_name')
    )
    op.create_table('item',
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('taken', 'stored', 'ended', name='itemstatus'), server_default='stored', nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('container')
    # ### end Alembic commands ###
